name: workflow1

on:
  push:
    branches:
    - main
    - dev
jobs:
  job1:
    runs-on: ubutntu-latest
    steps:
      - name: task 1 for printing OS details
        run: uname -a
      - name: task 2 to print hostname
        run: hostname
